import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import Script from "next/script";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeToggle } from "@/components/theme-toggle";
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});
export const metadata: Metadata = {
   title: "Dishant Gusain",
   description: "Generated by create next app",
   icons: {
      icon: "/animated-favicon.gif",
   },
};

export default async function RootLayout({
   children,
}: Readonly<{ children: React.ReactNode }>) {
   // Get theme from cookie for server-side rendering
   const cookieStore = await cookies();
   const theme = cookieStore.get("theme-preference")?.value || "dark"; // Default to dark if no cookie exists

   return (
      <html
         lang="en"
         suppressHydrationWarning
         className={theme}
      >
         <head />
         <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
         >
            <ThemeProvider>
               <div className="fixed top-8 right-14 z-50">
                  <ThemeToggle />
               </div>
               {children}
            </ThemeProvider>
         </body>
      </html>
   );
}
