import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeToggle } from "@/components/theme-toggle";
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});
export const metadata: Metadata = {
   title: "Dishant Gusain",
   description: "Generated by create next app",
   icons: {
      icon: '/animated-favicon.gif',
   },
};
export default function RootLayout({
   children,
}: Readonly<{ children: React.ReactNode }>) {
   return (
      <html
         lang="en"
         suppressHydrationWarning
      >
         <head />
         <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
         >
            <ThemeProvider defaultTheme="dark">
               <div className="fixed top-4 right-4 z-50">
                  <ThemeToggle />
               </div>
               {children}
            </ThemeProvider>
         </body>
      </html>
   );
}
